---
name: CI

on:
  push:
    branches: [ trunk ]

jobs:

  docs:
    name: Trigger pages generation
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check if any documentation related files changed.
        id: changed-documentation-files
        uses: tj-actions/changed-files@v12.2
        with:
          files: ^modules/
      - name: Trigger DAG-OS pages workflow
        if: steps.changed-documentation-files.outputs.any_changed == 'true'
        run: |
          curl \
            -X POST \
            -u "MLNW:${{ secrets.GIT_HUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/DAG-OS/pages/actions/workflows/publish.yml/dispatches \
            --data '{"ref": "trunk" }'
